-- Script para insertar 4 viviendas de ejemplo con TODOS los campos
-- Fecha: 2026-02-15
-- Usuario: id_usuario = 1 (ajusta según tu usuario)

USE gestor_viviendas;

-- Insertar 4 viviendas de ejemplo
INSERT INTO viviendas (
    id_usuario,
    nombre,
    calle,
    bloque_portal,
    piso,
    escalera,
    letra_numero,
    barrio,
    ciudad,
    pais,
    codigo_postal,
    direccion,
    tipo_vivienda,
    categoria,
    num_banos,
    num_habitaciones,
    capacidad_maxima,
    superficie,
    planta,
    ano_construccion,
    superficie_parcela,
    amenities,
    imagen_url,
    estado_legal,
    referencia_catastral,
    numero_registro_autonomico,
    fecha_registro,
    activa,
    latitud,
    longitud,
    url_ical_airbnb,
    url_ical_booking,
    url_booking,
    url_airbnb
) VALUES
-- Vivienda 1: Apartamento Céntrico Barcelona
(
    1,
    'Apartamento Céntrico Barcelona',
    'Carrer de Balmes',
    'Bloque A',
    '3',
    'Izquierda',
    'B',
    'Eixample',
    'Barcelona',
    'España',
    '08008',
    'Carrer de Balmes 123, 3º B, Barcelona',
    'Apartamento',
    'Vivienda de uso turístico',
    2,
    3,
    6,
    85.00,
    3,
    2015,
    NULL,
    '["wifi", "aire_acondicionado", "calefaccion", "cocina_equipada", "lavadora", "television", "ascensor", "balcon"]',
    NULL,
    'Legal',
    '5217702DF3851H0078BW',
    'VUT-B-00123456',
    '2024-01-15',
    1,
    41.39396110,
    2.16333970,
    'https://www.airbnb.com/calendar/ical/123456789.ics?s=abc123',
    'https://admin.booking.com/hotel/hoteladmin/ical.html?t=xyz789',
    'https://www.booking.com/hotel/es/apartamento-barcelona.html',
    'https://www.airbnb.es/rooms/123456789'
),
-- Vivienda 2: Estudio Moderno Madrid Centro
(
    1,
    'Estudio Moderno Madrid Centro',
    'Calle Gran Vía',
    'Portal 45',
    '5',
    'Centro',
    '2',
    'Centro',
    'Madrid',
    'España',
    '28013',
    'Calle Gran Vía 45, 5º 2, Madrid',
    'Estudio',
    'Apartamento turístico',
    1,
    1,
    2,
    45.00,
    5,
    2018,
    NULL,
    '["wifi", "aire_acondicionado", "calefaccion", "cocina_equipada", "ascensor", "parking"]',
    NULL,
    'Legal',
    '7234501VK4273S0023WX',
    'VT-MAD-00987654',
    '2023-06-20',
    1,
    40.42003500,
    -3.70577830,
    'https://www.airbnb.com/calendar/ical/987654321.ics?s=def456',
    'https://admin.booking.com/hotel/hoteladmin/ical.html?t=uvw321',
    'https://www.booking.com/hotel/es/estudio-madrid.html',
    'https://www.airbnb.es/rooms/987654321'
),
-- Vivienda 3: Chalet con Piscina Valencia
(
    1,
    'Chalet con Piscina Valencia',
    'Avenida de las Palmeras',
    'Chalet 78',
    NULL,
    NULL,
    NULL,
    'La Cañada',
    'Valencia',
    'España',
    '46182',
    'Avenida de las Palmeras 78, La Cañada, Valencia',
    'Chalet',
    'Casa rural',
    3,
    4,
    8,
    180.00,
    0,
    2010,
    450.00,
    '["wifi", "aire_acondicionado", "calefaccion", "cocina_equipada", "lavadora", "television", "piscina", "jardin", "barbacoa", "parking", "chimenea"]',
    NULL,
    'Legal',
    '9876543AB5678C0045YZ',
    'VT-46182-V',
    '2022-03-10',
    1,
    39.46990750,
    -0.37628830,
    'https://www.airbnb.com/calendar/ical/456789123.ics?s=ghi789',
    'https://admin.booking.com/hotel/hoteladmin/ical.html?t=rst654',
    'https://www.booking.com/hotel/es/chalet-valencia.html',
    'https://www.airbnb.es/rooms/456789123'
),
-- Vivienda 4: Ático con Terraza Sevilla
(
    1,
    'Ático con Terraza Sevilla',
    'Plaza Nueva',
    'Edificio 12',
    'Ático',
    'Derecha',
    'A',
    'Casco Antiguo',
    'Sevilla',
    'España',
    '41001',
    'Plaza Nueva 12, Ático A, Sevilla',
    'Ático',
    'Vivienda turística',
    2,
    2,
    4,
    95.00,
    6,
    2012,
    NULL,
    '["wifi", "aire_acondicionado", "calefaccion", "cocina_equipada", "lavadora", "television", "ascensor", "terraza", "vistas"]',
    NULL,
    'Legal',
    '4123456CD7890E0067MN',
    'VFT/SE/00567890',
    '2023-09-05',
    1,
    37.38916710,
    -5.99452980,
    'https://www.airbnb.com/calendar/ical/789456123.ics?s=jkl012',
    'https://admin.booking.com/hotel/hoteladmin/ical.html?t=opq987',
    'https://www.booking.com/hotel/es/atico-sevilla.html',
    'https://www.airbnb.es/rooms/789456123'
);

-- Verificar que se insertaron correctamente
SELECT 
    id_vivienda,
    nombre,
    ciudad,
    direccion,
    tipo_vivienda,
    num_habitaciones,
    num_banos,
    superficie,
    activa
FROM viviendas 
WHERE id_usuario = 1
ORDER BY id_vivienda DESC
LIMIT 10;
